### ISSUE TITLE
Errors on startup

### ISSUE THREAD

**Issue by pbucci** [oschneid/Macaron#10]
Every time you load Macaron there are like a million errors that pop up. They do not affect functionality. Someone needs to track down the source of these errors and resolve.

**Comment by oschneid** [comment]
@mchun345 have you resolved this? If so mark it closed and explain what you fixed!

**Comment by mchun345** [comment]
I fixed this in 2 ways, there was 1 error message relating to how the first example on the right hand side of the editor was not loading upon startup, I believe I made a reference to a particular example in examplesquare.jsx. 

I added a componentWillMount (v4) or something to this effect.

The firebase errors were suppressed by commenting out references to it in the other files, but this was only supposed to be a temporary thing for Haptics Symposium.
