### ISSUE TITLE
Startup example needs to load top selected waveform

### ISSUE THREAD

**Issue by pbucci** [oschneid/Macaron#13]
On startup, the example window has an arbitrary waveform. It's replaced as soon as you click. It should be the top example/automatically selected example.

**Comment by oschneid** [comment]
@mchun345 I think you solved this, let's mark it as resolved. Would be great if you could give the revision number too but if it's hard, just say branch and close.

**Comment by mchun345** [comment]
Sorry for the lack of revision number but this was fixed in examplesquare.jsx by giving a specific example to load in onComponentWillMount eg. v4

**Comment by mchun345** [comment]
Branch was called mc_fix_error_msgs_loadup_example
